include ../theos/makefiles/common.mk

LIBRARY_NAME = Toggle
Toggle_FILES = main.m
Toggle_INSTALL_PATH = /var/mobile/Library/SBSettings/Toggles/Quit Apps
Toggle_PRIVATE_FRAMEWORKS = AppSupport
Toggle_FRAMEWORKS = UIKit

include $(THEOS_MAKE_PATH)/library.mk
